import type {FieldCatalogItem,ObservationMarker} from '../lib/api'
import type {CubeMode,View} from '../App'

type Props={fields:FieldCatalogItem[];field:string;setField:(v:string)=>void;view:View;setView:(v:View)=>void;depth:number;setDepth:(v:number)=>void;depthMax:number;times:string[];timeIndex:number;setTimeIndex:(v:number)=>void;observations:ObservationMarker[];selected:ObservationMarker|null;selectedBuoys:ObservationMarker[];showObservations:boolean;setShowObservations:(v:boolean)=>void;selectRegion:boolean;selectBuoys:boolean;cubeActive:boolean;cubeMode:CubeMode;setCubeMode:(v:CubeMode)=>void;isoValue:number|null;isoMin:number;isoMax:number;setIsoValue:(v:number|null)=>void;onSelectRegion:()=>void;onSelectBuoys:()=>void;onCancelSelection:()=>void;onCommitBuoys:()=>void;onCloseCube:()=>void}
export function ControlPanel(p:Props){
 return <aside className="control-panel">
  <section className="control-section first-section"><div className="section-heading"><span>1. FIELD</span></div><select value={p.field} onChange={e=>p.setField(e.target.value)}>{p.fields.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></section>
  {!p.cubeActive&&<>
   <section className="control-section"><div className="section-heading"><span>2. VIEW</span></div><div className="view-list">{([['globe','GLOBE','Global field'],['slice','DEPTH SLICE','Field at depth'],['currents','CURRENTS','Surface flow']] as [View,string,string][]).map(([id,t,h])=><button key={id} className={`view-button ${p.view===id?'active':''}`} onClick={()=>p.setView(id)}><span>{t}</span><small>{h}</small></button>)}</div></section>
   <section className="control-section"><div className="section-heading"><span>3. TIME</span><b>{p.times[p.timeIndex]?.slice(0,10)??'—'}</b></div><input className="range" type="range" min="0" max={Math.max(0,p.times.length-1)} value={p.timeIndex} onChange={e=>p.setTimeIndex(+e.target.value)} disabled={!p.times.length}/><div className="range-labels"><span>Earlier</span><span>Later</span></div></section>
   <section className="control-section"><div className="section-heading"><span>4. DEPTH</span><b>{p.depth} m {p.depth===0?'(Surface)':''}</b></div><input className="range" type="range" min="0" max={p.depthMax} step="25" value={p.depth} onChange={e=>p.setDepth(+e.target.value)} /><div className="range-labels depth-labels"><span>0m</span><span>1000m</span><span>2000m</span><span>3000m</span><span>4000m</span><span>5000m</span></div></section>
   <section className="control-section"><div className="section-heading"><span>5. OBSERVATIONS</span><b>{p.observations.length}</b></div><button className={p.showObservations?'toggle active':'toggle'} onClick={()=>p.setShowObservations(!p.showObservations)}><span className="toggle-mark">{p.showObservations?'✓':''}</span>Show all Argo / instruments</button><button className={`selection-action ${p.selectRegion?'active':''}`} onClick={p.selectRegion?p.onCancelSelection:p.onSelectRegion}>{p.selectRegion?'CANCEL REGION':'SELECT A REGION'}</button><button className={`selection-action ${p.selectBuoys?'active':''}`} onClick={p.selectBuoys?p.onCancelSelection:p.onSelectBuoys}>{p.selectBuoys?'CANCEL BUOY SELECTION':'SELECT BUOYS'}</button>{p.selectBuoys&&<div className="selection-note">SELECTED: {p.selectedBuoys.length}<br/>Click instruments on the globe.</div>}{p.selectBuoys&&p.selectedBuoys.length>0&&<button className="selection-confirm" onClick={p.onCommitBuoys}>CREATE REGION</button>}</section>
  </>}
  {p.cubeActive&&<>
   <section className="control-section regional-controls"><div className="section-heading"><span>2. REGIONAL CUBE</span></div><div className="cube-region-label">3D field from surface to maximum available depth.</div><div className="view-list cube-view-list">{([['volume','VOLUME','Full 3D field'],['currents','CURRENTS','Regional surface flow']] as [CubeMode,string,string][]).map(([id,t,h])=><button key={id} className={`view-button ${p.cubeMode===id?'active':''}`} onClick={()=>p.setCubeMode(id)}><span>{t}</span><small>{h}</small></button>)}</div><div className="section-heading iso-heading"><span>ISOVALUE</span><b>{p.isoValue===null?'NONE':`${p.isoValue.toFixed(2)} ${p.fields.find(f=>f.id===p.field)?.units??''}`}</b></div><input className="range" type="range" min={p.isoMin} max={p.isoMax} step={(p.isoMax-p.isoMin)/200||.01} value={p.isoValue??p.isoMin} onChange={e=>p.setIsoValue(+e.target.value)}/><div className="range-labels"><span>{p.isoMin.toFixed(1)}</span><span>{p.isoMax.toFixed(1)}</span></div><button className={`iso-none ${p.isoValue===null?'active':''}`} onClick={()=>p.setIsoValue(null)}>NONE · SHOW FULL FIELD</button></section>
   <section className="control-section"><div className="section-heading"><span>3. TIME</span><b>{p.times[p.timeIndex]?.slice(0,10)??'—'}</b></div><input className="range" type="range" min="0" max={Math.max(0,p.times.length-1)} value={p.timeIndex} onChange={e=>p.setTimeIndex(+e.target.value)} disabled={!p.times.length}/><div className="range-labels"><span>Earlier</span><span>Later</span></div></section>
   <section className="control-section"><button className="selection-action active" onClick={p.onCloseCube}>CLOSE REGIONAL ANALYSIS</button></section>
  </>}
 </aside>
}
