import {useEffect,useRef} from 'react'
import * as THREE from 'three'
import Globe from 'globe.gl'
import type {FieldCatalogItem,ObservationMarker,SliceResponse,VectorFieldResponse,VolumeResponse} from '../lib/api'
import {normalizeScalarRange,paletteCss} from '../lib/volume'

type Props={view:'globe'|'slice'|'volume'|'iso';field:FieldCatalogItem|null;volume:VolumeResponse|null;slice:SliceResponse|null;currents:VectorFieldResponse|null;observations:ObservationMarker[];selected:ObservationMarker|null;opacity:number;exaggeration:number;onSelect:(m:ObservationMarker)=>void}
const R=100
const EARTH_TEXTURE='/earth/earth-blue-marble.jpg', EARTH_BUMP='/earth/earth-topology.png', EARTH_NIGHT='/earth/earth-night.jpg'
function geo(lat:number,lon:number,r=R){const p=THREE.MathUtils.degToRad(lat),l=THREE.MathUtils.degToRad(lon);return new THREE.Vector3(r*Math.cos(p)*Math.sin(l),r*Math.sin(p),r*Math.cos(p)*Math.cos(l))}
function basis(lat:number,lon:number){const p=THREE.MathUtils.degToRad(lat),l=THREE.MathUtils.degToRad(lon);return{east:new THREE.Vector3(Math.cos(l),0,-Math.sin(l)),north:new THREE.Vector3(-Math.sin(p)*Math.sin(l),Math.cos(p),-Math.sin(p)*Math.cos(l)),up:new THREE.Vector3(Math.cos(p)*Math.sin(l),Math.sin(p),Math.cos(p)*Math.cos(l))}}
function colorFor(value:number,min=0,max=1){return new THREE.Color(paletteCss(THREE.MathUtils.clamp((value-min)/(max-min||1),0,1)))}
function makeSurfaceTexture(slice:SliceResponse,opacity:number){
  const [ny,nx]=slice.shape, vals=normalizeScalarRange(slice.values,slice.bounds.min,slice.bounds.max,'linear',slice.missing_value)
  const canvas=document.createElement('canvas');canvas.width=nx;canvas.height=ny;const ctx=canvas.getContext('2d')!;const image=ctx.createImageData(nx,ny)
  for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const i=y*nx+x,v=vals[i],k=i*4;if(v<0){image.data[k+3]=0;continue}const c=colorFor(v);image.data[k]=c.r*255;image.data[k+1]=c.g*255;image.data[k+2]=c.b*255;image.data[k+3]=255}ctx.putImageData(image,0,0)
  const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;tex.minFilter=THREE.LinearFilter;tex.magFilter=THREE.LinearFilter
  const material=new THREE.ShaderMaterial({uniforms:{map:{value:tex},opacity:{value:opacity},lat0:{value:THREE.MathUtils.degToRad(slice.latitude[0])},lat1:{value:THREE.MathUtils.degToRad(slice.latitude.at(-1)!)},lon0:{value:THREE.MathUtils.degToRad(slice.longitude[0])},lon1:{value:THREE.MathUtils.degToRad(slice.longitude.at(-1)!)}},vertexShader:`varying vec3 vWorld;void main(){vec4 wp=modelMatrix*vec4(position,1.);vWorld=wp.xyz;gl_Position=projectionMatrix*viewMatrix*wp;}`,fragmentShader:`uniform sampler2D map;uniform float opacity,lat0,lat1,lon0,lon1;varying vec3 vWorld;void main(){vec3 n=normalize(vWorld);float lat=asin(clamp(n.y,-1.,1.));float lon=atan(n.x,n.z);float u=(lon-lon0)/(lon1-lon0),v=(lat-lat0)/(lat1-lat0);if(u<0.||u>1.||v<0.||v>1.)discard;vec4 c=texture2D(map,vec2(u,1.-v));if(c.a<.01)discard;gl_FragColor=vec4(c.rgb,c.a*opacity);}`,transparent:true,depthWrite:false,side:THREE.FrontSide})
  const mesh=new THREE.Mesh(new THREE.SphereGeometry(R*1.004,128,64),material);mesh.renderOrder=3;return mesh
}
function cubeFrame(v:VolumeResponse,ex:number){const lat0=v.latitude[0],lat1=v.latitude.at(-1)!,lon0=v.longitude[0],lon1=v.longitude.at(-1)!,d0=v.depth[0],d1=v.depth.at(-1)!,lat=(lat0+lat1)/2,lon=(lon0+lon1)/2,b=basis(lat,lon),w=Math.abs(lon1-lon0)*111.195*Math.cos(THREE.MathUtils.degToRad(lat))*R/6371,h=Math.abs(lat1-lat0)*111.195*R/6371,d=Math.abs(d1-d0)/1000*R/6371*Math.max(.5,ex*180),center=geo(lat,lon,R-d/2),q=new THREE.Quaternion().setFromRotationMatrix(new THREE.Matrix4().makeBasis(b.east,b.north,b.up.clone().negate()));return{w,h,d,center,q}}
function makeVolume(v:VolumeResponse,opacity:number,ex:number){
  const vals=normalizeScalarRange(v.values,v.bounds.min,v.bounds.max,'linear',v.missing_value),tex=new THREE.Data3DTexture(new Float32Array(vals),v.shape[2],v.shape[1],v.shape[0]);
  tex.format=THREE.RedFormat;tex.type=THREE.FloatType;tex.minFilter=THREE.LinearFilter;tex.magFilter=THREE.LinearFilter;tex.unpackAlignment=1;tex.needsUpdate=true;
  const {w,h,d,center,q}=cubeFrame(v,ex), inverse=new THREE.Matrix4();
  const mat=new THREE.ShaderMaterial({uniforms:{fieldTex:{value:tex},opacity:{value:opacity},steps:{value:Math.min(180,Math.max(80,v.shape[0]*6))},modelMatrixInverse:{value:inverse}},vertexShader:`varying vec3 vWorldPos;void main(){vWorldPos=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler3D fieldTex;uniform float opacity,steps;uniform mat4 modelMatrixInverse;varying vec3 vWorldPos;vec3 pal(float t){t=clamp(t,0.,1.);vec3 a=vec3(.03,.15,.36),b=vec3(.02,.68,.76),c=vec3(.96,.74,.19),d=vec3(.77,.08,.04);if(t<.33)return mix(a,b,t/.33);if(t<.66)return mix(b,c,(t-.33)/.33);return mix(c,d,(t-.66)/.34);}void main(){vec3 ro=(modelMatrixInverse*vec4(cameraPosition,1.)).xyz;vec3 rd=normalize((modelMatrixInverse*vec4(vWorldPos-cameraPosition,0.)).xyz);vec3 inv=1./rd;vec3 t0=(-vec3(.5)-ro)*inv;vec3 t1=(vec3(.5)-ro)*inv;vec3 lo=min(t0,t1),hi=max(t0,t1);float enter=max(max(lo.x,lo.y),lo.z),exit=min(min(hi.x,hi.y),hi.z);enter=max(enter,0.);if(exit<=enter)discard;float ds=(exit-enter)/steps;vec3 pos=ro+rd*enter;vec4 outc=vec4(0.);for(float i=0.;i<180.;i++){if(i>=steps||enter>=exit)break;float value=texture(fieldTex,pos+.5).r;float a=smoothstep(.05,.8,value)*opacity*.075;outc.rgb+=(1.-outc.a)*pal(value)*a;outc.a+=(1.-outc.a)*a;pos+=rd*ds;enter+=ds;if(outc.a>.96)break;}if(outc.a<.008)discard;gl_FragColor=outc;}`,side:THREE.BackSide,transparent:true,depthWrite:false});
  const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.copy(center);mesh.quaternion.copy(q);mesh.updateMatrixWorld(true);inverse.copy(mesh.matrixWorld).invert();mesh.renderOrder=4;return mesh
}
function makeIso(v:VolumeResponse,ex:number){const[nz,ny,nx]=v.shape,vals=normalizeScalarRange(v.values,v.bounds.min,v.bounds.max,'linear',v.missing_value),threshold=.58,{w,h,d,center,q}=cubeFrame(v,ex),pos:number[]=[];const c=[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]],tet=[[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6],[0,5,1,6]];const p=(x:number,y:number,z:number)=>new THREE.Vector3((x/(nx-1)-.5)*w,(.5-y/(ny-1))*h,(z/(nz-1)-.5)*d).applyQuaternion(q).add(center),val=(x:number,y:number,z:number)=>vals[z*ny*nx+y*nx+x],edge=(a:number[],b:number,va:number,vb:number)=>{const t=va===vb?.5:THREE.MathUtils.clamp((threshold-va)/(vb-va),0,1);return p(a[0]+(c[b][0]-a[0])*t,a[1]+(c[b][1]-a[1])*t,a[2]+(c[b][2]-a[2])*t)};for(let z=0;z<nz-1;z++)for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){const cv=c.map(q0=>val(x+q0[0],y+q0[1],z+q0[2]));if(cv.some(vv=>vv<0))continue;for(const ti of tet){const ins=ti.filter(i=>cv[i]>=threshold),out=ti.filter(i=>cv[i]<threshold);if(!ins.length||ins.length===4)continue;if(ins.length===1||ins.length===3){const one=ins.length===1?ins[0]:out[0],o=ins.length===1?out:ins;const a=edge(c[one],o[0],cv[one],cv[o[0]]),b=edge(c[one],o[1],cv[one],cv[o[1]]),d0=edge(c[one],o[2],cv[one],cv[o[2]]);for(const pp of ins.length===1?[a,b,d0]:[a,d0,b])pos.push(pp.x,pp.y,pp.z)}else{const[a,b]=ins,[c0,d0]=out,p1=edge(c[a],c0,cv[a],cv[c0]),p2=edge(c[a],d0,cv[a],cv[d0]),p3=edge(c[b],c0,cv[b],cv[c0]),p4=edge(c[b],d0,cv[b],cv[d0]);for(const pp of[p1,p2,p3,p2,p4,p3])pos.push(pp.x,pp.y,pp.z)}}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0xf1b84b,transparent:true,opacity:.82,side:THREE.DoubleSide,roughness:.7}));m.renderOrder=5;return m}
function makeCurrents(v:VectorFieldResponse,opacity:number){const group=new THREE.Group(),lines:number[]=[];const ny=v.latitude.length,nx=v.longitude.length,step=Math.max(1,Math.ceil(Math.max(ny,nx)/22)),axis=new THREE.Vector3(0,1,0);for(let y=0;y<ny;y+=step)for(let x=0;x<nx;x+=step){const i=y*nx+x,u=v.u[i],vv=v.v[i];if(!Number.isFinite(u)||!Number.isFinite(vv)||u===-9999||vv===-9999)continue;const base=geo(v.latitude[y],v.longitude[x],R*1.012),b=basis(v.latitude[y],v.longitude[x]),vec=b.east.clone().multiplyScalar(u).add(b.north.clone().multiplyScalar(vv)),mag=vec.length();if(mag<.002)continue;const dir=vec.normalize(),len=Math.min(3.2,.45+mag*5),tip=base.clone().add(dir.clone().multiplyScalar(len));lines.push(base.x,base.y,base.z,tip.x,tip.y,tip.z);const cone=new THREE.Mesh(new THREE.ConeGeometry(.17,.6,6),new THREE.MeshBasicMaterial({color:0x65e5f3,transparent:true,opacity}));cone.position.copy(tip);cone.quaternion.setFromUnitVectors(axis,dir);group.add(cone)}const lg=new THREE.BufferGeometry();lg.setAttribute('position',new THREE.Float32BufferAttribute(lines,3));group.add(new THREE.LineSegments(lg,new THREE.LineBasicMaterial({color:0x65e5f3,transparent:true,opacity})));group.renderOrder=6;return group}
export function OceanScene({view,field,volume,slice,currents,observations,selected,onSelect,opacity,exaggeration}:Props){const ref=useRef<HTMLDivElement>(null),gRef=useRef<any>(null),resources=useRef<THREE.Object3D[]>([]);useEffect(()=>{if(!ref.current)return;const host=ref.current,g=new Globe(host,{animateIn:false,waitForGlobeReady:true}).backgroundColor('#02080d').globeImageUrl(EARTH_TEXTURE).bumpImageUrl(EARTH_BUMP).backgroundImageUrl(EARTH_NIGHT).showAtmosphere(true).atmosphereColor('#4dd8ee').atmosphereAltitude(.11).showGraticules(true).pointsData(observations).pointLat('latitude').pointLng('longitude').pointColor((d:any)=>selected?.platform===d.platform?'#ffd166':'#62e5f3').pointAltitude(.025).pointRadius((d:any)=>selected?.platform===d.platform?.75:.38).pointResolution(8).pointLabel((d:any)=>`${d.platform} · cycle ${d.cycle}`).onPointClick((d:any)=>onSelect(d));g.controls().enableDamping=true;g.controls().dampingFactor=.08;g.controls().minDistance=120;g.controls().maxDistance=520;g.pointOfView({lat:18,lng:78,altitude:1.9});gRef.current=g;(window as any).__OCEAN_GLOBE__=g;const resize=()=>{g.width(host.clientWidth);g.height(host.clientHeight)};const ro=new ResizeObserver(resize);ro.observe(host);resize();return()=>{ro.disconnect();resources.current.forEach(o=>o.traverse((x:any)=>{x.geometry?.dispose?.();x.material?.map?.dispose?.();x.material?.dispose?.()}));g.customLayerData([]);g._destructor();gRef.current=null;(window as any).__OCEAN_GLOBE__=null}},[onSelect]);useEffect(()=>{const g=gRef.current;if(!g)return;(window as any).__OCEAN_DEBUG__={view,fieldId:field?.id??null,opacity,exaggeration,hasVolume:!!volume,hasSlice:!!slice,hasCurrents:!!currents,observationCount:observations.length};resources.current.forEach(o=>o.traverse((x:any)=>{x.geometry?.dispose?.();x.material?.map?.dispose?.();x.material?.dispose?.()}));const layers:THREE.Object3D[]=[];if(slice&&field?.id!=='currents'&&(view==='globe'||view==='slice'))layers.push(makeSurfaceTexture(slice,opacity));if(currents&&field?.id==='currents')layers.push(makeCurrents(currents,opacity));if(view==='volume'&&volume)layers.push(makeVolume(volume,opacity,exaggeration));if(view==='iso'&&volume)layers.push(makeIso(volume,exaggeration));resources.current=layers;g.showGlobe(true);g.customLayerData(layers).customThreeObject((d:any)=>d).customThreeObjectUpdate((obj:any)=>{obj.visible=true});g.pointsData(observations).pointColor((d:any)=>selected?.platform===d.platform?'#ffd166':'#62e5f3').pointRadius((d:any)=>selected?.platform===d.platform?.75:.38);g.controls().update()},[view,field,volume,slice,currents,observations,selected,opacity,exaggeration]);return <div ref={ref} className="ocean-scene" aria-label="Interactive geographic ocean analysis globe"/>}
