import {useEffect,useRef} from 'react'
import * as THREE from 'three'
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js'
import {feature} from 'topojson-client'
import countries from 'world-atlas/countries-110m.json'
import type {FieldCatalogItem,ObservationMarker,ProfileResponse,SliceResponse,VectorFieldResponse,VolumeResponse} from '../lib/api'
import {normalizeScalarRange,paletteCss} from '../lib/volume'

type Props={view:'globe'|'slice'|'volume'|'section'|'iso';field:FieldCatalogItem|null;volume:VolumeResponse|null;slice:SliceResponse|null;currents:VectorFieldResponse|null;observations:ObservationMarker[];selected:ObservationMarker|null;profile:ProfileResponse|null;opacity:number;exaggeration:number;onSelect:(m:ObservationMarker)=>void}

const vertex=`varying vec3 vUv;void main(){vUv=position*.5+.5;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`
const fragment=`uniform sampler3D fieldTex;uniform float opacity;uniform float steps;varying vec3 vUv;vec3 pal(float t){t=clamp(t,0.,1.);vec3 a=vec3(.03,.15,.36),b=vec3(.02,.68,.76),c=vec3(.96,.74,.19),d=vec3(.77,.08,.04);if(t<.33)return mix(a,b,t/.33);if(t<.66)return mix(b,c,(t-.33)/.33);return mix(c,d,(t-.66)/.34);}void main(){vec3 q=vUv;vec3 ray=normalize(vec3(.10,-.06,1.0));float ds=1.0/steps;vec4 outc=vec4(0.);for(float i=0.;i<220.;i++){if(i>=steps||any(lessThan(q,vec3(0.)))||any(greaterThan(q,vec3(1.))))break;float v=texture(fieldTex,q).r;float a=smoothstep(.02,.72,v)*opacity*.085;outc.rgb+=(1.-outc.a)*pal(v)*a;outc.a+=(1.-outc.a)*a;if(outc.a>.96)break;q+=ray*ds;}if(outc.a<.008)discard;gl_FragColor=outc;}`

function geo(lat:number,lon:number,r=2){const p=THREE.MathUtils.degToRad(lat),l=THREE.MathUtils.degToRad(lon);return new THREE.Vector3(r*Math.cos(p)*Math.cos(l),r*Math.sin(p),r*Math.cos(p)*Math.sin(l))}
function colorFor(value:number,min:number,max:number){return new THREE.Color(paletteCss(THREE.MathUtils.clamp((value-min)/(max-min||1),0,1)))}
function makeGlobe(){return new THREE.Mesh(new THREE.SphereGeometry(2,128,80),new THREE.MeshStandardMaterial({color:0x061b25,roughness:1,metalness:0,transparent:true,opacity:.96}))}
function makeAtmosphere(){return new THREE.Mesh(new THREE.SphereGeometry(2.045,96,64),new THREE.MeshBasicMaterial({color:0x1c8da4,transparent:true,opacity:.055,side:THREE.BackSide}))}
function makeCoastlines(){const g=new THREE.Group();const geojson:any=feature(countries as any,(countries as any).objects.countries);const add=(coords:any[])=>{for(const line of coords){const pts=line.map((p:any)=>geo(p[1],p[0],2.012));const b=new THREE.BufferGeometry().setFromPoints(pts);g.add(new THREE.Line(b,new THREE.LineBasicMaterial({color:0x4b9aaa,transparent:true,opacity:.48})))}};for(const f of geojson.features){const c=f.geometry?.coordinates;if(f.geometry?.type==='Polygon')add(c);if(f.geometry?.type==='MultiPolygon')c.forEach((p:any)=>add(p))}return g}
function makeFieldTexture(slice:SliceResponse,opacity=.92){const c=document.createElement('canvas');c.width=1024;c.height=512;const ctx=c.getContext('2d')!;const image=ctx.createImageData(c.width,c.height);const vals=normalizeScalarRange(slice.values,slice.bounds.min,slice.bounds.max,'linear',slice.missing_value);const ny=slice.shape[0],nx=slice.shape[1];for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const v=vals[y*nx+x];if(v<0)continue;const px=Math.round((slice.longitude[x]+180)/360*(c.width-1)),py=Math.round((90-slice.latitude[y])/180*(c.height-1));const col=colorFor(v,0,1);for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const xx=px+dx,yy=py+dy;if(xx<0||xx>=c.width||yy<0||yy>=c.height)continue;const i=(yy*c.width+xx)*4;image.data[i]=col.r*255;image.data[i+1]=col.g*255;image.data[i+2]=col.b*255;image.data[i+3]=Math.round(opacity*235)}}ctx.putImageData(image,0,0);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return tex}
function makeMarkers(markers:ObservationMarker[],selected:ObservationMarker|null,onSelect:(m:ObservationMarker)=>void){const g=new THREE.Group();const matA=new THREE.MeshBasicMaterial({color:0x58e7f4});const matB=new THREE.MeshBasicMaterial({color:0xffd166});for(const m of markers){const mesh=new THREE.Mesh(new THREE.SphereGeometry(selected?.platform===m.platform?.045:.022,8,6),selected?.platform===m.platform?matB:matA);mesh.position.copy(geo(m.latitude,m.longitude,2.055));mesh.userData.marker=m;g.add(mesh)}return g}
function makeCurrents(v:VectorFieldResponse){const pts:number[]=[];const cols:number[]=[];const ny=v.latitude.length,nx=v.longitude.length;for(let y=0;y<ny;y+=2)for(let x=0;x<nx;x+=2){const i=y*nx+x,u=v.u[i],vv=v.v[i];if(u===-9999||vv===-9999)continue;const a=geo(v.latitude[y],v.longitude[x],2.03);const b=geo(v.latitude[y]+vv*1.8,v.longitude[x]+u*1.8,2.03);pts.push(a.x,a.y,a.z,b.x,b.y,b.z);cols.push(.3,.86,.94,.96,.7,.25)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));g.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));return new THREE.LineSegments(g,new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.82}))}
function makeRoiOutline(lat0:number,lat1:number,lon0:number,lon1:number){const pts=[geo(lat0,lon0,2.07),geo(lat0,lon1,2.07),geo(lat1,lon1,2.07),geo(lat1,lon0,2.07),geo(lat0,lon0,2.07)];return new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0xffd166,transparent:true,opacity:.9}))}
function makeVolume(volume:VolumeResponse,opacity:number,exaggeration:number){const vals=normalizeScalarRange(volume.values,volume.bounds.min,volume.bounds.max,'linear',volume.missing_value);const tex=new THREE.Data3DTexture(vals,volume.shape[2],volume.shape[1],volume.shape[0]);tex.format=THREE.RedFormat;tex.type=THREE.FloatType;tex.minFilter=THREE.LinearFilter;tex.magFilter=THREE.LinearFilter;tex.unpackAlignment=1;tex.needsUpdate=true;const mat=new THREE.ShaderMaterial({uniforms:{fieldTex:{value:tex},opacity:{value:opacity},steps:{value:Math.min(180,Math.max(80,volume.shape[0]*7))}},vertexShader:vertex,fragmentShader:fragment,side:THREE.BackSide,transparent:true,depthWrite:false});const box=new THREE.Mesh(new THREE.BoxGeometry(2.75,1.3*exaggeration,2.05),mat);box.position.set(0,.03,-.08);return box}
function makeIso(volume:VolumeResponse){const [nz,ny,nx]=volume.shape;const vals=normalizeScalarRange(volume.values,volume.bounds.min,volume.bounds.max,'linear',volume.missing_value);const p:number[]=[];const t=.58;const c=[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]];const tet=[[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6],[0,5,1,6]];const point=(x:number,y:number,z:number)=>new THREE.Vector3((x/(nx-1)-.5)*2.75,.68-z/(nz-1)*1.3,(y/(ny-1)-.5)*2.05-.08);const value=(x:number,y:number,z:number)=>vals[z*ny*nx+y*nx+x];const interp=(a:number[],b:number[],va:number,vb:number)=>{const q=va===vb?.5:THREE.MathUtils.clamp((t-va)/(vb-va),0,1);return point(a[0]+(b[0]-a[0])*q,a[1]+(b[1]-a[1])*q,a[2]+(b[2]-a[2])*q)};for(let z=0;z<nz-1;z++)for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){const cv=c.map(q=>value(x+q[0],y+q[1],z+q[2]));if(cv.some(v=>v<0))continue;for(const ti of tet){const inside=ti.filter(i=>cv[i]>=t),outside=ti.filter(i=>cv[i]<t);if(!inside.length||inside.length===4)continue;if(inside.length===1||inside.length===3){const one=inside.length===1?inside[0]:outside[0],others=inside.length===1?outside:inside;const a=interp(c[one],c[others[0]],cv[one],cv[others[0]]),b=interp(c[one],c[others[1]],cv[one],cv[others[1]]),d=interp(c[one],c[others[2]],cv[one],cv[others[2]]);if(inside.length===1)p.push(a.x,a.y,a.z,b.x,b.y,b.z,d.x,d.y,d.z);else p.push(a.x,a.y,a.z,d.x,d.y,d.z,b.x,b.y,b.z)}else{const[a,b]=inside,[c0,d]=outside;const p1=interp(c[a],c[c0],cv[a],cv[c0]),p2=interp(c[a],c[d],cv[a],cv[d]),p3=interp(c[b],c[c0],cv[b],cv[c0]),p4=interp(c[b],c[d],cv[b],cv[d]);p.push(p1.x,p1.y,p1.z,p2.x,p2.y,p2.z,p3.x,p3.y,p3.z,p2.x,p2.y,p2.z,p4.x,p4.y,p4.z,p3.x,p3.y,p3.z)}}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.computeVertexNormals();return new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0xffc14d,transparent:true,opacity:.72,side:THREE.DoubleSide,roughness:.8}))}
function makeSection(volume:VolumeResponse){const[nz,ny,nx]=volume.shape;const vals=normalizeScalarRange(volume.values,volume.bounds.min,volume.bounds.max,'linear',volume.missing_value);const mid=Math.floor(ny/2),p:number[]=[],colors:number[]=[];for(let z=0;z<nz-1;z++)for(let x=0;x<nx-1;x++){const idx=[z*ny*nx+mid*nx+x,z*ny*nx+mid*nx+x+1,(z+1)*ny*nx+mid*nx+x+1,(z+1)*ny*nx+mid*nx+x],xx=[x,x+1,x+1,x],zz=[z,z,z+1,z+1],tri=[0,1,2,0,2,3];for(const k of tri){const v=vals[idx[k]];p.push((xx[k]/(nx-1)-.5)*2.75,.03,(.5-zz[k]/(nz-1))*1.3-.08);const c=colorFor(v<0?.5:v,0,1);colors.push(c.r,c.g,c.b)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));return new THREE.Mesh(g,new THREE.MeshBasicMaterial({vertexColors:true,side:THREE.DoubleSide,transparent:true,opacity:.95}))}

export function OceanScene({view,field,volume,slice,currents,observations,selected,profile,opacity,exaggeration,onSelect}:Props){const ref=useRef<HTMLDivElement>(null);const state=useRef<any>(null)
useEffect(()=>{if(!ref.current)return;const host=ref.current,scene=new THREE.Scene();scene.background=new THREE.Color('#02080d');const cam=new THREE.PerspectiveCamera(38,host.clientWidth/Math.max(1,host.clientHeight),.01,100);cam.position.set(4.6,2.35,4.8);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);const controls=new OrbitControls(cam,renderer.domElement);controls.enableDamping=true;controls.minDistance=2.35;controls.maxDistance=12;const hemi=new THREE.HemisphereLight(0x9fe8ff,0x021018,1.5),key=new THREE.DirectionalLight(0xffffff,1.2);key.position.set(4,4,6);scene.add(hemi,key);const root=new THREE.Group();scene.add(root);root.add(makeGlobe(),makeAtmosphere(),makeCoastlines());state.current={scene,cam,renderer,controls,root};const render=()=>renderer.render(scene,cam);controls.addEventListener('change',render);const resize=()=>{cam.aspect=host.clientWidth/Math.max(1,host.clientHeight);cam.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);render()};const ro=new ResizeObserver(resize);ro.observe(host);render();return()=>{controls.removeEventListener('change',render);ro.disconnect();controls.dispose();renderer.dispose();host.removeChild(renderer.domElement);state.current=null}},[])
useEffect(()=>{const s=state.current;if(!s)return;const root=s.root;while(root.children.length>3){const o=root.children.pop();o?.traverse((x:any)=>{x.geometry?.dispose?.();if(x.material){x.material.map?.dispose?.();x.material.dispose?.()}})}const globe=root.children[0] as THREE.Mesh;const coast=root.children[2];if(slice&&field?.id!=='currents'){globe.material=new THREE.MeshBasicMaterial({map:makeFieldTexture(slice),transparent:true,opacity:.94});globe.material.needsUpdate=true}else{globe.material=new THREE.MeshStandardMaterial({color:0x061b25,roughness:1})}root.add(makeMarkers(observations,selected,onSelect));if(currents&&field?.id==='currents')root.add(makeCurrents(currents));if(slice&&field?.id!=='currents'&&slice.latitude.length&&slice.longitude.length)root.add(makeRoiOutline(Math.min(...slice.latitude),Math.max(...slice.latitude),Math.min(...slice.longitude),Math.max(...slice.longitude)));if(view==='volume'&&volume)root.add(makeVolume(volume,opacity,exaggeration));if(view==='iso'&&volume)root.add(makeIso(volume));if(view==='section'&&volume)root.add(makeSection(volume));if(view==='slice'&&slice){const plane=new THREE.Mesh(new THREE.PlaneGeometry(2.7,1.28),new THREE.MeshBasicMaterial({map:makeFieldTexture(slice),transparent:true,opacity:.88,side:THREE.DoubleSide}));plane.position.set(0,-.04,.15);plane.rotation.x=-.12;root.add(plane)}s.renderer.render(s.scene,s.cam)},[view,field,volume,slice,currents,observations,selected,profile,opacity,exaggeration,onSelect])
useEffect(()=>{const s=state.current;if(!s)return;const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();const fn=(e:PointerEvent)=>{const r=s.renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,s.cam);const hit=ray.intersectObjects(s.root.children,true).find((h:any)=>h.object.userData.marker);if(hit)onSelect(hit.object.userData.marker)};const reset=()=>{s.cam.position.set(4.6,2.35,4.8);s.controls.target.set(0,0,0);s.controls.update()};s.renderer.domElement.addEventListener('pointerup',fn);s.renderer.domElement.addEventListener('dblclick',reset);return()=>{s.renderer.domElement.removeEventListener('pointerup',fn);s.renderer.domElement.removeEventListener('dblclick',reset)}},[onSelect])
return <div ref={ref} className="ocean-scene" aria-label="Interactive 3D ocean analysis globe"/>}
