import {lazy,Suspense,useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {ControlPanel} from './components/ControlPanel'
import {getComparison,getCube,getFields,getObservations,getProfile,getSlice,getCurrents,getTimes,type ComparisonResponse,type FieldCatalogItem,type ObservationMarker,type ProfileResponse,type SliceResponse,type VectorFieldResponse,type VolumeResponse} from './lib/api'
import './styles/app.css'

const OceanScene=lazy(()=>import('./components/OceanScene').then(m=>({default:m.OceanScene})))
export type View='globe'|'slice'|'currents'
export type CubeMode='volume'|'currents'
export type Region={latMin:number;latMax:number;lonMin:number;lonMax:number}

function formatTime(value?:string){return value?value.replace('T',' ').replace(/:00Z$/,' UTC'):'—'}
function rangeOf(data:SliceResponse|VolumeResponse|null,field:FieldCatalogItem|null){return data?data.bounds:{min:field?.color_min??0,max:field?.color_max??1}}
function currentRange(data:VectorFieldResponse|null){if(!data)return{min:0,max:1};let max=0;for(let i=0;i<data.u.length;i++){const u=data.u[i],v=data.v[i];if(Number.isFinite(u)&&Number.isFinite(v))max=Math.max(max,Math.hypot(u,v))}return{min:0,max:max||1}}
function useCommitted<T>(value:T,delay=120){const[committed,setCommitted]=useState(value);const timer=useRef<number|null>(null);useEffect(()=>{if(timer.current!==null)window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>setCommitted(value),delay);return()=>{if(timer.current!==null)window.clearTimeout(timer.current)}},[value,delay]);return[committed,setCommitted] as const}

export default function App(){
 const[fields,setFields]=useState<FieldCatalogItem[]>([]),[field,setField]=useState('temperature'),[view,setView]=useState<View>('globe')
 const[times,setTimes]=useState<string[]>([]),[timeIndex,setTimeIndex]=useState(0),[depth,setDepth]=useState(0)
 const[volume,setVolume]=useState<VolumeResponse|null>(null),[slice,setSlice]=useState<SliceResponse|null>(null),[currents,setCurrents]=useState<VectorFieldResponse|null>(null)
 const[obs,setObs]=useState<ObservationMarker[]>([]),[showObs,setShowObs]=useState(true),[selected,setSelected]=useState<ObservationMarker|null>(null),[selectedBuoys,setSelectedBuoys]=useState<ObservationMarker[]>([])
 const[profile,setProfile]=useState<ProfileResponse|null>(null),[comparison,setComparison]=useState<ComparisonResponse|null>(null)
 const[error,setError]=useState(''),[loading,setLoading]=useState(false),[requestCount,setRequestCount]=useState(0),[cacheHits,setCacheHits]=useState(0)
 const[region,setRegion]=useState<Region|null>(null),[selectRegion,setSelectRegion]=useState(false),[selectBuoys,setSelectBuoys]=useState(false),[cubeActive,setCubeActive]=useState(false),[cubeMode,setCubeMode]=useState<CubeMode>('volume'),[isoValue,setIsoValue]=useState(20)
 const[timeCommitted]=useCommitted(timeIndex),[depthCommitted]=useCommitted(depth)
 const cacheRef=useRef(new Set<string>())

 useEffect(()=>{Promise.all([getFields(),getObservations()]).then(([f,o])=>{setFields(f);setObs(o)}).catch(e=>setError(e.message))},[])
 useEffect(()=>{let alive=true;getTimes(field).then(ts=>{if(alive){setTimes(ts);setTimeIndex(i=>Math.min(i,Math.max(0,ts.length-1)))}}).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[field])
 useEffect(()=>{let alive=true;setError('');if(cubeActive&&region){const key=`cube:${field}:${timeCommitted}:${region.latMin}:${region.latMax}:${region.lonMin}:${region.lonMax}`;const cached=cacheRef.current.has(key);if(cached)setCacheHits(v=>v+1);setLoading(!cached);const cubeTask=getCube(field,region,1,timeCommitted).then(v=>{if(!alive)return;cacheRef.current.add(key);setVolume(v)});const currentTask=cubeMode==='currents'?getCurrents().then(v=>alive&&setCurrents(v)):Promise.resolve();Promise.allSettled([cubeTask,currentTask]).then(results=>{if(!alive)return;const failed=results.find(r=>r.status==='rejected') as PromiseRejectedResult|undefined;if(failed)setError(failed.reason?.message??'Regional data unavailable')}).finally(()=>alive&&setLoading(false));setRequestCount(v=>v+1+(cubeMode==='currents'?1:0));return()=>{alive=false}}
 const key=view==='currents'?'currents':`${field}:${view}:${depthCommitted}:${timeCommitted}`;const cached=cacheRef.current.has(key);if(cached)setCacheHits(v=>v+1);setLoading(!cached)
 if(view==='currents'){getCurrents().then(v=>alive&&setCurrents(v)).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));setRequestCount(v=>v+1);return()=>{alive=false}}
 getSlice(field,view==='globe'?0:depthCommitted,2,timeCommitted).then(v=>{if(!alive)return;cacheRef.current.add(key);setSlice(v)}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));setRequestCount(v=>v+1);return()=>{alive=false}
 },[field,view,depthCommitted,timeCommitted,cubeActive,region])

 const select=useCallback((m:ObservationMarker)=>{setSelected(m);setProfile(null);setComparison(null);Promise.allSettled([getProfile(m.platform,m.cycle),getComparison(m.platform,m.cycle,field)]).then(r=>{if(r[0].status==='fulfilled')setProfile(r[0].value);if(r[1].status==='fulfilled')setComparison(r[1].value)}).catch(()=>undefined)},[field])
 const changeField=(v:string)=>{setField(v);setSelected(null);setProfile(null);setComparison(null)}
 const clearSelection=()=>{setSelectRegion(false);setSelectBuoys(false);setSelectedBuoys([]);setSelected(null)}
 const pickRegion=(lat:number,lon:number)=>{const halfLat=4.5,halfLon=5;setRegion({latMin:Math.max(-29,lat-halfLat),latMax:Math.min(29,lat+halfLat),lonMin:Math.max(31,lon-halfLon),lonMax:Math.min(119,lon+halfLon)});setSelectRegion(false);setSelectBuoys(false);setSelectedBuoys([]);setCubeActive(true);setCubeMode('volume')}
 const startBuoys=()=>{setSelected(null);setSelectedBuoys([]);setSelectRegion(false);setSelectBuoys(true)}
 const toggleBuoy=(m:ObservationMarker)=>{if(!selectBuoys){select(m);return}setSelectedBuoys(v=>v.some(x=>x.platform===m.platform&&x.cycle===m.cycle)?v.filter(x=>!(x.platform===m.platform&&x.cycle===m.cycle)):[...v,m])}
 const commitBuoys=()=>{if(!selectedBuoys.length)return;const lats=selectedBuoys.map(x=>x.latitude),lons=selectedBuoys.map(x=>x.longitude);const padLat=Math.max(2,Math.min(6,(Math.max(...lats)-Math.min(...lats))*.22)),padLon=Math.max(2,Math.min(6,(Math.max(...lons)-Math.min(...lons))*.22));setRegion({latMin:Math.max(-29,Math.min(...lats)-padLat),latMax:Math.min(29,Math.max(...lats)+padLat),lonMin:Math.max(31,Math.min(...lons)-padLon),lonMax:Math.min(119,Math.max(...lons)+padLon)});setSelectBuoys(false);setCubeActive(true);setCubeMode('volume')}
 const closeCube=()=>{setCubeActive(false);setRegion(null);setCubeMode('volume');setSelectedBuoys([]);setView('globe')}
 const current=fields.find(f=>f.id===field)??null, scalar=rangeOf(slice,current), crange=currentRange(currents), activeTime=view==='currents'?currents?.valid_time:times[timeIndex]
 const isoMin=volume?.bounds.min??current?.color_min??0,isoMax=volume?.bounds.max??current?.color_max??1
 useEffect(()=>{if(volume)setIsoValue(v=>Math.min(isoMax,Math.max(isoMin,v||((isoMin+isoMax)/2))))},[volume,isoMin,isoMax])
 const info=useMemo(()=>({field:view==='currents'?'Surface Currents':current?.label??'Ocean field',units:view==='currents'?'m s⁻¹':current?.units??'—',source:view==='currents'?currents?.source:current?.source,time:activeTime,depth:view==='globe'?0:depthCommitted,min:view==='currents'?crange.min:scalar.min,max:view==='currents'?crange.max:scalar.max}),[view,current,currents,activeTime,depthCommitted,scalar.min,scalar.max,crange.min,crange.max])
 const cubeInfo=cubeActive&&volume?{min:volume.bounds.min,max:volume.bounds.max}:info
 const statusText=error?'SOURCE ERROR':loading?'UPDATING DATA':'SOURCE CONNECTED'
 return <main className="app"><header className="topbar"><div className="brand"><div className="brand-mark">O</div><div><strong>OCEAN ANALYSIS CONSOLE</strong><small>SIH26067 · MVP</small></div></div><div className="status"><span className={`status-dot ${error?'error-status':loading?'loading-status':'connected'}`}/>{statusText}<span className="status-sep"/>INCOIS / ARGO<span className="status-sep"/>{formatTime(cubeActive?volume?.valid_time:activeTime)}</div></header>
 <div className="workspace"><ControlPanel fields={fields.filter(f=>f.id!=='currents')} field={field} setField={changeField} view={view} setView={setView} depth={depth} setDepth={setDepth} depthMax={5000} times={times} timeIndex={timeIndex} setTimeIndex={setTimeIndex} observations={obs} selected={selected} selectedBuoys={selectedBuoys} showObservations={showObs} setShowObservations={setShowObs} selectRegion={selectRegion} selectBuoys={selectBuoys} cubeActive={cubeActive} cubeMode={cubeMode} setCubeMode={setCubeMode} isoValue={isoValue} isoMin={isoMin} isoMax={isoMax} setIsoValue={setIsoValue} onSelectRegion={()=>{setSelectRegion(true);setSelectBuoys(false)}} onSelectBuoys={startBuoys} onCancelSelection={clearSelection} onCommitBuoys={commitBuoys} onCloseCube={closeCube}/>
 <section className="viewport"><div className="viewport-title"><span className="eyebrow">{cubeActive?'REGIONAL 3D ANALYSIS':view==='globe'?'GLOBAL VIEW':view==='slice'?'DEPTH SLICE':'SURFACE FLOW'}</span><h1>{cubeActive?`${current?.label??'Field'} · SELECTED REGION`:info.field}</h1><p>{cubeActive?`${volume?.source??current?.source??'Loading source…'} · ${current?.units??'—'} · ${formatTime(volume?.valid_time??times[timeIndex])}`: `${info.source??'Loading source…'} · ${info.units} · ${formatTime(info.time)}`}</p></div>
 {loading&&<div className="data-progress"><span/>UPDATING FIELD</div>}{error&&<div className="error">{error}</div>}
 <Suspense fallback={<div className="loading">INITIALIZING 3D ENGINE…</div>}><OceanScene view={view} cubeActive={cubeActive} cubeMode={cubeMode} isoValue={isoValue} region={region} field={current} volume={volume} slice={slice} currents={currents} observations={showObs?obs:[]} selected={selected} selectedBuoys={selectedBuoys} selectRegion={selectRegion} onSelect={toggleBuoy} onRegionPick={pickRegion} opacity={.86} exaggeration={1}/></Suspense>
 <aside className="data-stack"><section className="data-card"><div className="card-title">DATA INFO</div><div className="kv"><span>Field</span><b>{cubeActive?current?.label:info.field}</b></div><div className="kv"><span>Units</span><b>{cubeActive?current?.units:info.units}</b></div><div className="kv"><span>Source</span><b>{cubeActive?(volume?.source??current?.source):info.source??'—'}</b></div><div className="kv"><span>Time</span><b>{formatTime(cubeActive?volume?.valid_time:info.time)}</b></div><div className="kv"><span>Depth</span><b>{cubeActive?'0 → max depth':`${info.depth} m`}</b></div><div className="kv"><span>Min / Max</span><b>{cubeInfo.min.toFixed(2)} / {cubeInfo.max.toFixed(2)} {cubeActive?current?.units:info.units}</b></div>{cubeActive&&region&&<div className="region-meta"><span>REGION</span><b>{region.latMin.toFixed(1)}°–{region.latMax.toFixed(1)}° N / {region.lonMin.toFixed(1)}°–{region.lonMax.toFixed(1)}° E</b></div>}</section>
 <section className="data-card argo-card"><div className="card-title">ARGO / INSTRUMENTS</div><div className="argo-summary"><span>Total</span><b>{obs.length}</b><span>Selected</span><b>{cubeActive?selectedBuoys.length:selected?1:0}</b></div>{selected&&<div className="selected-mini"><span>SELECTED</span><b>{selected.platform}</b><small>{selected.latitude.toFixed(3)}° · {selected.longitude.toFixed(3)}° · cycle {selected.cycle}</small></div>}</section>
 <section className="data-card legend-card"><div className="card-title">LEGEND</div><div className="legend-name">{(cubeActive?current?.label:info.field)?.toUpperCase()} <span>({cubeActive?current?.units:info.units})</span></div><div className="legend-gradient"/><div className="legend-ticks"><span>{cubeInfo.min.toFixed(1)}</span><span>{((cubeInfo.min+cubeInfo.max)/2).toFixed(1)}</span><span>{cubeInfo.max.toFixed(1)}</span></div><div className="legend-extents"><span>Min: {cubeInfo.min.toFixed(2)}</span><span>Max: {cubeInfo.max.toFixed(2)}</span></div>{cubeActive&&<div className="iso-legend"><i/> isovalue {isoValue.toFixed(2)}</div>}{view==='currents'&&!cubeActive&&<div className="vector-key"><i/> direction · magnitude</div>}</section>
 {cubeActive&&<section className="data-card cube-actions"><div className="card-title">3D ANALYSIS</div><div className="cube-readout"><span>VOLUME</span><b>ACTIVE</b></div><div className="cube-readout"><span>ISOVALUE</span><b>{isoValue.toFixed(2)} {current?.units}</b></div><div className="cube-readout"><span>CURRENT</span><b>{cubeMode==='currents'?'ACTIVE':'AVAILABLE'}</b></div><button onClick={closeCube}>CLOSE REGIONAL ANALYSIS</button></section>}
 </aside>
 {selectRegion&&<div className="selection-help">CLICK THE GLOBE TO SET A SMALL REGIONAL WINDOW</div>}
 <div className="scene-hint">DRAG = ROTATE &nbsp; | &nbsp; SCROLL = ZOOM &nbsp; | &nbsp; R = RESET</div><div className="render-status">REQUESTS: {requestCount} &nbsp; | &nbsp; CACHE HITS: {cacheHits} &nbsp; | &nbsp; ARGO: {obs.length}</div></section></div></main>
}
