import {lazy,Suspense,useCallback,useEffect,useState} from 'react'
import {ControlPanel} from './components/ControlPanel'
import {ProfileInspector} from './components/ProfileInspector'
import {ProvenancePanel} from './components/ProvenancePanel'
import {getComparison,getFields,getObservations,getProfile,getSlice,getVolume,getCurrents,type ComparisonResponse,type FieldCatalogItem,type ObservationMarker,type ProfileResponse,type SliceResponse,type VectorFieldResponse,type VolumeResponse} from './lib/api'
import './styles/app.css'
const OceanScene=lazy(()=>import('./components/OceanScene').then(m=>({default:m.OceanScene})))
export default function App(){
 const[fields,setFields]=useState<FieldCatalogItem[]>([]);const[field,setField]=useState('temperature');const[view,setView]=useState<'globe'|'slice'|'volume'|'section'|'iso'>('globe');const[depth,setDepth]=useState(100);const[opacity,setOpacity]=useState(.82);const[exaggeration,setExaggeration]=useState(1.3);const[volume,setVolume]=useState<VolumeResponse|null>(null);const[slice,setSlice]=useState<SliceResponse|null>(null);const[currents,setCurrents]=useState<VectorFieldResponse|null>(null);const[obs,setObs]=useState<ObservationMarker[]>([]);const[selected,setSelected]=useState<ObservationMarker|null>(null);const[profile,setProfile]=useState<ProfileResponse|null>(null);const[comparison,setComparison]=useState<ComparisonResponse|null>(null);const[error,setError]=useState('');
 useEffect(()=>{Promise.all([getFields(),getObservations()]).then(([f,o])=>{setFields(f);setObs(o);if(f.length&&!f.some(x=>x.id===field))setField(f[0].id)}).catch(e=>setError(e.message))},[])
 useEffect(()=>{let alive=true;setError('');setVolume(null);setSlice(null);setCurrents(null);if(field==='currents'){getCurrents().then(v=>alive&&setCurrents(v)).catch(e=>alive&&setError(e.message));return()=>{alive=false}} Promise.all([getVolume(field,2),getSlice(field,depth,2)]).then(([v,s])=>{if(alive){setVolume(v);setSlice(s)}}).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[field,depth])
 const select=useCallback((m:ObservationMarker)=>{setSelected(m);Promise.all([getProfile(m.platform,m.cycle),getComparison(m.platform,m.cycle,field==='salinity'?'salinity':'temperature')]).then(([p,c])=>{setProfile(p);setComparison(c)}).catch(e=>setError(e.message))},[field])
 const current=fields.find(f=>f.id===field)??null
 return <main className="app"><header><div className="brand"><div className="brand-icon">O</div><div><strong>OCEAN ANALYSIS CONSOLE</strong><small>SIH26067 · 3D OCEAN SITUATIONAL ANALYSIS</small></div></div><div className="header-right"><span className="live">● LIVE DATA</span><span>INDIAN OCEAN · INCOIS</span></div></header><div className="main-grid"><ControlPanel fields={fields} field={field} setField={v=>{setField(v);if(v==='currents')setView('globe')}} view={view} setView={setView} depth={depth} setDepth={setDepth} opacity={opacity} setOpacity={setOpacity} exaggeration={exaggeration} setExaggeration={setExaggeration} observations={obs} selected={selected} onSelect={select}/><section className="viewport"><div className="viewport-head"><div><span className="eyebrow">{view.toUpperCase()}</span><h1>{current?.label??'Ocean field'}</h1><p>{current?.source??'Acquiring live data…'} · {current?.units??''}</p></div><div className="legend"><span>LOW</span><i/><span>HIGH</span></div></div>{error&&<div className="error">{error}</div>}<Suspense fallback={<div className="loading">INITIALIZING GPU SCENE…</div>}><OceanScene view={view} field={current} volume={volume} slice={slice} currents={currents} observations={obs} selected={selected} profile={profile} opacity={opacity} exaggeration={exaggeration} onSelect={select}/></Suspense><div className="scene-hint">DRAG ROTATE · WHEEL ZOOM · CLICK FLOAT TO INSPECT</div></section></div><div className="bottom"><ProfileInspector profile={profile} comparison={comparison}/><ProvenancePanel field={current}/></div></main>}
