import {lazy,Suspense,useCallback,useEffect,useState} from 'react'
import {ControlPanel} from './components/ControlPanel'
import {ProfileInspector} from './components/ProfileInspector'
import {ProvenancePanel} from './components/ProvenancePanel'
import {RightInspector} from './components/RightInspector'
import {DebugPanel} from './components/DebugPanel'
import {getComparison,getFields,getObservations,getProfile,getSlice,getVolume,getCurrents,getTimes,type ComparisonResponse, type FieldCatalogItem,type ObservationMarker,type ProfileResponse,type SliceResponse,type VectorFieldResponse,type VolumeResponse} from './lib/api'
import './styles/app.css'
const OceanScene=lazy(()=>import('./components/OceanScene').then(m=>({default:m.OceanScene})))
export default function App(){const[fields,setFields]=useState<FieldCatalogItem[]>([]),[field,setField]=useState('temperature'),[times,setTimes]=useState<string[]>([]),[timeIndex,setTimeIndex]=useState(0),[view,setView]=useState<'globe'|'slice'|'volume'|'iso'>('globe'),[depth,setDepth]=useState(100),[opacity,setOpacity]=useState(.72),[exaggeration,setExaggeration]=useState(1.25),[volume,setVolume]=useState<VolumeResponse|null>(null),[slice,setSlice]=useState<SliceResponse|null>(null),[currents,setCurrents]=useState<VectorFieldResponse|null>(null),[obs,setObs]=useState<ObservationMarker[]>([]),[selected,setSelected]=useState<ObservationMarker|null>(null),[profile,setProfile]=useState<ProfileResponse|null>(null),[comparison,setComparison]=useState<ComparisonResponse|null>(null),[error,setError]=useState('')
useEffect(()=>{Promise.all([getFields(),getObservations()]).then(([f,o])=>{setFields(f);setObs(o)}).catch(e=>setError(e.message))},[])
useEffect(()=>{let alive=true;setError('');setVolume(null);setSlice(null);setCurrents(null);if(field==='currents'){getCurrents().then(v=>alive&&setCurrents(v)).catch(e=>alive&&setError(e.message));return()=>{alive=false}}getTimes(field).then(ts=>{if(alive){setTimes(ts);setTimeIndex(Math.max(0,ts.length-1))}}).catch(()=>{});return()=>{alive=false}},[field])
useEffect(()=>{if(field==='currents')return;let alive=true;setVolume(null);setSlice(null);Promise.all([getVolume(field,2,timeIndex),getSlice(field,depth,1,timeIndex)]).then(([v,s])=>{if(alive){setVolume(v);setSlice(s)}}).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[field,depth,timeIndex])
const select=useCallback((m:ObservationMarker)=>{setSelected(m);Promise.all([getProfile(m.platform,m.cycle),getComparison(m.platform,m.cycle,field==='salinity'?'salinity':'temperature')]).then(([p,c])=>{setProfile(p);setComparison(c)}).catch(e=>setError(e.message))},[field]);const current=fields.find(f=>f.id===field)??null
return <main className="app"><header><div className="brand"><div className="brand-icon">O</div><div><strong>OCEAN ANALYSIS CONSOLE</strong><small>SIH26067 · INDIAN OCEAN SCIENTIFIC WORKSPACE</small></div></div><div className="header-right"><span className="live">● REAL DATA</span><span>{current?.source??'INCOIS'}</span></div></header><div className="main-grid"><ControlPanel fields={fields} field={field} setField={v=>{setField(v);if(v==='currents')setView('globe')}} view={view} setView={setView} depth={depth} setDepth={setDepth} opacity={opacity} setOpacity={setOpacity} exaggeration={exaggeration} setExaggeration={setExaggeration} times={times} timeIndex={timeIndex} setTimeIndex={setTimeIndex} observations={obs} selected={selected} onSelect={select}/><section className="viewport"><div className="viewport-head"><div><span className="eyebrow">{view.toUpperCase()}</span><h1>{current?.label??'Ocean field'}</h1><p>{current?.source??'Loading scientific field…'} · {current?.units??''}{times[timeIndex]?` · valid ${times[timeIndex].slice(0,10)}`:''}</p></div><div className="legend"><span>{current?.color_min??'—'}</span><i/><span>{current?.color_max??'—'} {current?.units??''}</span></div></div>{error&&<div className="error">{error}</div>}<Suspense fallback={<div className="loading">INITIALIZING SCIENTIFIC RENDERER…</div>}><OceanScene view={view} field={current} volume={volume} slice={slice} currents={currents} observations={obs} selected={selected} opacity={opacity} exaggeration={exaggeration} onSelect={select}/></Suspense><DebugPanel field={current} slice={slice} volume={volume} currents={currents} view={view} depth={depth} timeIndex={timeIndex} time={times[timeIndex]} opacity={opacity} exaggeration={exaggeration}/><div className="scene-hint">DRAG ROTATE · WHEEL ZOOM · CLICK FLOAT · RESET WITH DOUBLE-CLICK</div></section></div><RightInspector selected={selected} profile={profile} comparison={comparison} field={current}/><div className="bottom"><ProfileInspector profile={profile} comparison={comparison}/><ProvenancePanel field={current}/></div></main>}
